; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino_nano_esp32]
platform = espressif32@^6.5.0
board = arduino_nano_esp32
framework = arduino
board_build.filesystem = littlefs
; upload_protocol = esptool  ; (B1 + GND (turn purple) -> Upload file system ) (';' remove when upload add back after)
board_build.partitions = app3M_spiffs9M_fact512k_16MB.csv
monitor_speed = 115200
upload_speed = 115200
board_build.mcu = esp32s3
build_flags = 
	-D BOARD_USES_HW_GPIO_NUMBERS
lib_deps = 
	adafruit/RTClib@^2.1.4
	adafruit/Adafruit ILI9341@^1.6.3
	bodmer/TFT_eSPI@^2.5.43
	bblanchon/ArduinoJson@^7.2.2
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	dfrobot/DFRobot_DF1201S@^1.0.2
	plerup/EspSoftwareSerial@^8.2.0
